// Code generated by entc, DO NOT EDIT.

package semester

const (
	// Label holds the string label denoting the semester type in the database.
	Label = "semester"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSemestername holds the string denoting the semestername field in the database.
	FieldSemestername = "semestername"

	// EdgeSemesterID holds the string denoting the semesterid edge name in mutations.
	EdgeSemesterID = "SemesterID"

	// Table holds the table name of the semester in the database.
	Table = "semesters"
	// SemesterIDTable is the table the holds the SemesterID relation/edge.
	SemesterIDTable = "scholarships"
	// SemesterIDInverseTable is the table name for the Scholarship entity.
	// It exists in this package in order to avoid circular dependency with the "scholarship" package.
	SemesterIDInverseTable = "scholarships"
	// SemesterIDColumn is the table column denoting the SemesterID relation/edge.
	SemesterIDColumn = "semester_semester_id"
)

// Columns holds all SQL columns for semester fields.
var Columns = []string{
	FieldID,
	FieldSemestername,
}

var (
	// SemesternameValidator is a validator for the "Semestername" field. It is called by the builders before save.
	SemesternameValidator func(string) error
)
