// Code generated by entc, DO NOT EDIT.

package semester

import (
	"github.com/Varissara/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Semestername applies equality check predicate on the "Semestername" field. It's identical to SemesternameEQ.
func Semestername(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSemestername), v))
	})
}

// SemesternameEQ applies the EQ predicate on the "Semestername" field.
func SemesternameEQ(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSemestername), v))
	})
}

// SemesternameNEQ applies the NEQ predicate on the "Semestername" field.
func SemesternameNEQ(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSemestername), v))
	})
}

// SemesternameIn applies the In predicate on the "Semestername" field.
func SemesternameIn(vs ...string) predicate.Semester {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSemestername), v...))
	})
}

// SemesternameNotIn applies the NotIn predicate on the "Semestername" field.
func SemesternameNotIn(vs ...string) predicate.Semester {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Semester(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSemestername), v...))
	})
}

// SemesternameGT applies the GT predicate on the "Semestername" field.
func SemesternameGT(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSemestername), v))
	})
}

// SemesternameGTE applies the GTE predicate on the "Semestername" field.
func SemesternameGTE(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSemestername), v))
	})
}

// SemesternameLT applies the LT predicate on the "Semestername" field.
func SemesternameLT(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSemestername), v))
	})
}

// SemesternameLTE applies the LTE predicate on the "Semestername" field.
func SemesternameLTE(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSemestername), v))
	})
}

// SemesternameContains applies the Contains predicate on the "Semestername" field.
func SemesternameContains(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSemestername), v))
	})
}

// SemesternameHasPrefix applies the HasPrefix predicate on the "Semestername" field.
func SemesternameHasPrefix(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSemestername), v))
	})
}

// SemesternameHasSuffix applies the HasSuffix predicate on the "Semestername" field.
func SemesternameHasSuffix(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSemestername), v))
	})
}

// SemesternameEqualFold applies the EqualFold predicate on the "Semestername" field.
func SemesternameEqualFold(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSemestername), v))
	})
}

// SemesternameContainsFold applies the ContainsFold predicate on the "Semestername" field.
func SemesternameContainsFold(v string) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSemestername), v))
	})
}

// HasSemesterID applies the HasEdge predicate on the "SemesterID" edge.
func HasSemesterID() predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SemesterIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SemesterIDTable, SemesterIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSemesterIDWith applies the HasEdge predicate on the "SemesterID" edge with a given conditions (other predicates).
func HasSemesterIDWith(preds ...predicate.Scholarship) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SemesterIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SemesterIDTable, SemesterIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Semester) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Semester) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Semester) predicate.Semester {
	return predicate.Semester(func(s *sql.Selector) {
		p(s.Not())
	})
}
