// Code generated by entc, DO NOT EDIT.

package studyplan

const (
	// Label holds the string label denoting the studyplan type in the database.
	Label = "studyplan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStudyplanname holds the string denoting the studyplanname field in the database.
	FieldStudyplanname = "studyplanname"

	// EdgeStudyplanID holds the string denoting the studyplanid edge name in mutations.
	EdgeStudyplanID = "StudyplanID"

	// Table holds the table name of the studyplan in the database.
	Table = "studyplans"
	// StudyplanIDTable is the table the holds the StudyplanID relation/edge.
	StudyplanIDTable = "scholarships"
	// StudyplanIDInverseTable is the table name for the Scholarship entity.
	// It exists in this package in order to avoid circular dependency with the "scholarship" package.
	StudyplanIDInverseTable = "scholarships"
	// StudyplanIDColumn is the table column denoting the StudyplanID relation/edge.
	StudyplanIDColumn = "studyplan_studyplan_id"
)

// Columns holds all SQL columns for studyplan fields.
var Columns = []string{
	FieldID,
	FieldStudyplanname,
}

var (
	// StudyplannameValidator is a validator for the "Studyplanname" field. It is called by the builders before save.
	StudyplannameValidator func(string) error
)
