// Code generated by entc, DO NOT EDIT.

package studyplan

import (
	"github.com/Varissara/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Studyplanname applies equality check predicate on the "Studyplanname" field. It's identical to StudyplannameEQ.
func Studyplanname(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameEQ applies the EQ predicate on the "Studyplanname" field.
func StudyplannameEQ(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameNEQ applies the NEQ predicate on the "Studyplanname" field.
func StudyplannameNEQ(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameIn applies the In predicate on the "Studyplanname" field.
func StudyplannameIn(vs ...string) predicate.Studyplan {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Studyplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStudyplanname), v...))
	})
}

// StudyplannameNotIn applies the NotIn predicate on the "Studyplanname" field.
func StudyplannameNotIn(vs ...string) predicate.Studyplan {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Studyplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStudyplanname), v...))
	})
}

// StudyplannameGT applies the GT predicate on the "Studyplanname" field.
func StudyplannameGT(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameGTE applies the GTE predicate on the "Studyplanname" field.
func StudyplannameGTE(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameLT applies the LT predicate on the "Studyplanname" field.
func StudyplannameLT(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameLTE applies the LTE predicate on the "Studyplanname" field.
func StudyplannameLTE(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameContains applies the Contains predicate on the "Studyplanname" field.
func StudyplannameContains(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameHasPrefix applies the HasPrefix predicate on the "Studyplanname" field.
func StudyplannameHasPrefix(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameHasSuffix applies the HasSuffix predicate on the "Studyplanname" field.
func StudyplannameHasSuffix(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameEqualFold applies the EqualFold predicate on the "Studyplanname" field.
func StudyplannameEqualFold(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStudyplanname), v))
	})
}

// StudyplannameContainsFold applies the ContainsFold predicate on the "Studyplanname" field.
func StudyplannameContainsFold(v string) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStudyplanname), v))
	})
}

// HasStudyplanID applies the HasEdge predicate on the "StudyplanID" edge.
func HasStudyplanID() predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StudyplanIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StudyplanIDTable, StudyplanIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStudyplanIDWith applies the HasEdge predicate on the "StudyplanID" edge with a given conditions (other predicates).
func HasStudyplanIDWith(preds ...predicate.Scholarship) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StudyplanIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StudyplanIDTable, StudyplanIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Studyplan) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Studyplan) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Studyplan) predicate.Studyplan {
	return predicate.Studyplan(func(s *sql.Selector) {
		p(s.Not())
	})
}
