// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldUseremail holds the string denoting the useremail field in the database.
	FieldUseremail = "useremail"

	// EdgeUserID holds the string denoting the userid edge name in mutations.
	EdgeUserID = "UserID"

	// Table holds the table name of the user in the database.
	Table = "users"
	// UserIDTable is the table the holds the UserID relation/edge.
	UserIDTable = "scholarships"
	// UserIDInverseTable is the table name for the Scholarship entity.
	// It exists in this package in order to avoid circular dependency with the "scholarship" package.
	UserIDInverseTable = "scholarships"
	// UserIDColumn is the table column denoting the UserID relation/edge.
	UserIDColumn = "user_user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldUseremail,
}

var (
	// UsernameValidator is a validator for the "Username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// UseremailValidator is a validator for the "Useremail" field. It is called by the builders before save.
	UseremailValidator func(string) error
)
