// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Educationlevel is the predicate function for educationlevel builders.
type Educationlevel func(*sql.Selector)

// Scholarship is the predicate function for scholarship builders.
type Scholarship func(*sql.Selector)

// Scholarshiptype is the predicate function for scholarshiptype builders.
type Scholarshiptype func(*sql.Selector)

// Semester is the predicate function for semester builders.
type Semester func(*sql.Selector)

// Studyplan is the predicate function for studyplan builders.
type Studyplan func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
