// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Varissara/app/ent/educationlevel"
	"github.com/Varissara/app/ent/predicate"
	"github.com/Varissara/app/ent/scholarship"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// EducationlevelUpdate is the builder for updating Educationlevel entities.
type EducationlevelUpdate struct {
	config
	hooks      []Hook
	mutation   *EducationlevelMutation
	predicates []predicate.Educationlevel
}

// Where adds a new predicate for the builder.
func (eu *EducationlevelUpdate) Where(ps ...predicate.Educationlevel) *EducationlevelUpdate {
	eu.predicates = append(eu.predicates, ps...)
	return eu
}

// SetEducationlevelname sets the Educationlevelname field.
func (eu *EducationlevelUpdate) SetEducationlevelname(s string) *EducationlevelUpdate {
	eu.mutation.SetEducationlevelname(s)
	return eu
}

// AddEducationlevelIDIDs adds the EducationlevelID edge to Scholarship by ids.
func (eu *EducationlevelUpdate) AddEducationlevelIDIDs(ids ...int) *EducationlevelUpdate {
	eu.mutation.AddEducationlevelIDIDs(ids...)
	return eu
}

// AddEducationlevelID adds the EducationlevelID edges to Scholarship.
func (eu *EducationlevelUpdate) AddEducationlevelID(s ...*Scholarship) *EducationlevelUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return eu.AddEducationlevelIDIDs(ids...)
}

// Mutation returns the EducationlevelMutation object of the builder.
func (eu *EducationlevelUpdate) Mutation() *EducationlevelMutation {
	return eu.mutation
}

// RemoveEducationlevelIDIDs removes the EducationlevelID edge to Scholarship by ids.
func (eu *EducationlevelUpdate) RemoveEducationlevelIDIDs(ids ...int) *EducationlevelUpdate {
	eu.mutation.RemoveEducationlevelIDIDs(ids...)
	return eu
}

// RemoveEducationlevelID removes EducationlevelID edges to Scholarship.
func (eu *EducationlevelUpdate) RemoveEducationlevelID(s ...*Scholarship) *EducationlevelUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return eu.RemoveEducationlevelIDIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (eu *EducationlevelUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := eu.mutation.Educationlevelname(); ok {
		if err := educationlevel.EducationlevelnameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Educationlevelname", err: fmt.Errorf("ent: validator failed for field \"Educationlevelname\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EducationlevelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EducationlevelUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EducationlevelUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EducationlevelUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EducationlevelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   educationlevel.Table,
			Columns: educationlevel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: educationlevel.FieldID,
			},
		},
	}
	if ps := eu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Educationlevelname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: educationlevel.FieldEducationlevelname,
		})
	}
	if nodes := eu.mutation.RemovedEducationlevelIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.EducationlevelIDTable,
			Columns: []string{educationlevel.EducationlevelIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.EducationlevelIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.EducationlevelIDTable,
			Columns: []string{educationlevel.EducationlevelIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{educationlevel.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// EducationlevelUpdateOne is the builder for updating a single Educationlevel entity.
type EducationlevelUpdateOne struct {
	config
	hooks    []Hook
	mutation *EducationlevelMutation
}

// SetEducationlevelname sets the Educationlevelname field.
func (euo *EducationlevelUpdateOne) SetEducationlevelname(s string) *EducationlevelUpdateOne {
	euo.mutation.SetEducationlevelname(s)
	return euo
}

// AddEducationlevelIDIDs adds the EducationlevelID edge to Scholarship by ids.
func (euo *EducationlevelUpdateOne) AddEducationlevelIDIDs(ids ...int) *EducationlevelUpdateOne {
	euo.mutation.AddEducationlevelIDIDs(ids...)
	return euo
}

// AddEducationlevelID adds the EducationlevelID edges to Scholarship.
func (euo *EducationlevelUpdateOne) AddEducationlevelID(s ...*Scholarship) *EducationlevelUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return euo.AddEducationlevelIDIDs(ids...)
}

// Mutation returns the EducationlevelMutation object of the builder.
func (euo *EducationlevelUpdateOne) Mutation() *EducationlevelMutation {
	return euo.mutation
}

// RemoveEducationlevelIDIDs removes the EducationlevelID edge to Scholarship by ids.
func (euo *EducationlevelUpdateOne) RemoveEducationlevelIDIDs(ids ...int) *EducationlevelUpdateOne {
	euo.mutation.RemoveEducationlevelIDIDs(ids...)
	return euo
}

// RemoveEducationlevelID removes EducationlevelID edges to Scholarship.
func (euo *EducationlevelUpdateOne) RemoveEducationlevelID(s ...*Scholarship) *EducationlevelUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return euo.RemoveEducationlevelIDIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (euo *EducationlevelUpdateOne) Save(ctx context.Context) (*Educationlevel, error) {
	if v, ok := euo.mutation.Educationlevelname(); ok {
		if err := educationlevel.EducationlevelnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Educationlevelname", err: fmt.Errorf("ent: validator failed for field \"Educationlevelname\": %w", err)}
		}
	}

	var (
		err  error
		node *Educationlevel
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EducationlevelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EducationlevelUpdateOne) SaveX(ctx context.Context) *Educationlevel {
	e, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return e
}

// Exec executes the query on the entity.
func (euo *EducationlevelUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EducationlevelUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EducationlevelUpdateOne) sqlSave(ctx context.Context) (e *Educationlevel, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   educationlevel.Table,
			Columns: educationlevel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: educationlevel.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Educationlevel.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := euo.mutation.Educationlevelname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: educationlevel.FieldEducationlevelname,
		})
	}
	if nodes := euo.mutation.RemovedEducationlevelIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.EducationlevelIDTable,
			Columns: []string{educationlevel.EducationlevelIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.EducationlevelIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   educationlevel.EducationlevelIDTable,
			Columns: []string{educationlevel.EducationlevelIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	e = &Educationlevel{config: euo.config}
	_spec.Assign = e.assignValues
	_spec.ScanValues = e.scanValues()
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{educationlevel.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return e, nil
}
