// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Varissara/app/ent/predicate"
	"github.com/Varissara/app/ent/scholarship"
	"github.com/Varissara/app/ent/scholarshiptype"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ScholarshiptypeUpdate is the builder for updating Scholarshiptype entities.
type ScholarshiptypeUpdate struct {
	config
	hooks      []Hook
	mutation   *ScholarshiptypeMutation
	predicates []predicate.Scholarshiptype
}

// Where adds a new predicate for the builder.
func (su *ScholarshiptypeUpdate) Where(ps ...predicate.Scholarshiptype) *ScholarshiptypeUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetScholarshiptypename sets the Scholarshiptypename field.
func (su *ScholarshiptypeUpdate) SetScholarshiptypename(s string) *ScholarshiptypeUpdate {
	su.mutation.SetScholarshiptypename(s)
	return su
}

// AddScholarshiptypeIDIDs adds the ScholarshiptypeID edge to Scholarship by ids.
func (su *ScholarshiptypeUpdate) AddScholarshiptypeIDIDs(ids ...int) *ScholarshiptypeUpdate {
	su.mutation.AddScholarshiptypeIDIDs(ids...)
	return su
}

// AddScholarshiptypeID adds the ScholarshiptypeID edges to Scholarship.
func (su *ScholarshiptypeUpdate) AddScholarshiptypeID(s ...*Scholarship) *ScholarshiptypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddScholarshiptypeIDIDs(ids...)
}

// Mutation returns the ScholarshiptypeMutation object of the builder.
func (su *ScholarshiptypeUpdate) Mutation() *ScholarshiptypeMutation {
	return su.mutation
}

// RemoveScholarshiptypeIDIDs removes the ScholarshiptypeID edge to Scholarship by ids.
func (su *ScholarshiptypeUpdate) RemoveScholarshiptypeIDIDs(ids ...int) *ScholarshiptypeUpdate {
	su.mutation.RemoveScholarshiptypeIDIDs(ids...)
	return su
}

// RemoveScholarshiptypeID removes ScholarshiptypeID edges to Scholarship.
func (su *ScholarshiptypeUpdate) RemoveScholarshiptypeID(s ...*Scholarship) *ScholarshiptypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveScholarshiptypeIDIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *ScholarshiptypeUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Scholarshiptypename(); ok {
		if err := scholarshiptype.ScholarshiptypenameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Scholarshiptypename", err: fmt.Errorf("ent: validator failed for field \"Scholarshiptypename\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScholarshiptypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScholarshiptypeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScholarshiptypeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScholarshiptypeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ScholarshiptypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scholarshiptype.Table,
			Columns: scholarshiptype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scholarshiptype.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Scholarshiptypename(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scholarshiptype.FieldScholarshiptypename,
		})
	}
	if nodes := su.mutation.RemovedScholarshiptypeIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshiptypeIDTable,
			Columns: []string{scholarshiptype.ScholarshiptypeIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ScholarshiptypeIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshiptypeIDTable,
			Columns: []string{scholarshiptype.ScholarshiptypeIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scholarshiptype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ScholarshiptypeUpdateOne is the builder for updating a single Scholarshiptype entity.
type ScholarshiptypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *ScholarshiptypeMutation
}

// SetScholarshiptypename sets the Scholarshiptypename field.
func (suo *ScholarshiptypeUpdateOne) SetScholarshiptypename(s string) *ScholarshiptypeUpdateOne {
	suo.mutation.SetScholarshiptypename(s)
	return suo
}

// AddScholarshiptypeIDIDs adds the ScholarshiptypeID edge to Scholarship by ids.
func (suo *ScholarshiptypeUpdateOne) AddScholarshiptypeIDIDs(ids ...int) *ScholarshiptypeUpdateOne {
	suo.mutation.AddScholarshiptypeIDIDs(ids...)
	return suo
}

// AddScholarshiptypeID adds the ScholarshiptypeID edges to Scholarship.
func (suo *ScholarshiptypeUpdateOne) AddScholarshiptypeID(s ...*Scholarship) *ScholarshiptypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddScholarshiptypeIDIDs(ids...)
}

// Mutation returns the ScholarshiptypeMutation object of the builder.
func (suo *ScholarshiptypeUpdateOne) Mutation() *ScholarshiptypeMutation {
	return suo.mutation
}

// RemoveScholarshiptypeIDIDs removes the ScholarshiptypeID edge to Scholarship by ids.
func (suo *ScholarshiptypeUpdateOne) RemoveScholarshiptypeIDIDs(ids ...int) *ScholarshiptypeUpdateOne {
	suo.mutation.RemoveScholarshiptypeIDIDs(ids...)
	return suo
}

// RemoveScholarshiptypeID removes ScholarshiptypeID edges to Scholarship.
func (suo *ScholarshiptypeUpdateOne) RemoveScholarshiptypeID(s ...*Scholarship) *ScholarshiptypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveScholarshiptypeIDIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *ScholarshiptypeUpdateOne) Save(ctx context.Context) (*Scholarshiptype, error) {
	if v, ok := suo.mutation.Scholarshiptypename(); ok {
		if err := scholarshiptype.ScholarshiptypenameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Scholarshiptypename", err: fmt.Errorf("ent: validator failed for field \"Scholarshiptypename\": %w", err)}
		}
	}

	var (
		err  error
		node *Scholarshiptype
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScholarshiptypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScholarshiptypeUpdateOne) SaveX(ctx context.Context) *Scholarshiptype {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *ScholarshiptypeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScholarshiptypeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ScholarshiptypeUpdateOne) sqlSave(ctx context.Context) (s *Scholarshiptype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scholarshiptype.Table,
			Columns: scholarshiptype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scholarshiptype.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Scholarshiptype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Scholarshiptypename(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scholarshiptype.FieldScholarshiptypename,
		})
	}
	if nodes := suo.mutation.RemovedScholarshiptypeIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshiptypeIDTable,
			Columns: []string{scholarshiptype.ScholarshiptypeIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ScholarshiptypeIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshiptypeIDTable,
			Columns: []string{scholarshiptype.ScholarshiptypeIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Scholarshiptype{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scholarshiptype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
