// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Varissara/app/ent/scholarship"
	"github.com/Varissara/app/ent/scholarshiptype"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ScholarshiptypeCreate is the builder for creating a Scholarshiptype entity.
type ScholarshiptypeCreate struct {
	config
	mutation *ScholarshiptypeMutation
	hooks    []Hook
}

// SetScholarshiptypename sets the Scholarshiptypename field.
func (sc *ScholarshiptypeCreate) SetScholarshiptypename(s string) *ScholarshiptypeCreate {
	sc.mutation.SetScholarshiptypename(s)
	return sc
}

// AddScholarshiptypeIDIDs adds the ScholarshiptypeID edge to Scholarship by ids.
func (sc *ScholarshiptypeCreate) AddScholarshiptypeIDIDs(ids ...int) *ScholarshiptypeCreate {
	sc.mutation.AddScholarshiptypeIDIDs(ids...)
	return sc
}

// AddScholarshiptypeID adds the ScholarshiptypeID edges to Scholarship.
func (sc *ScholarshiptypeCreate) AddScholarshiptypeID(s ...*Scholarship) *ScholarshiptypeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddScholarshiptypeIDIDs(ids...)
}

// Mutation returns the ScholarshiptypeMutation object of the builder.
func (sc *ScholarshiptypeCreate) Mutation() *ScholarshiptypeMutation {
	return sc.mutation
}

// Save creates the Scholarshiptype in the database.
func (sc *ScholarshiptypeCreate) Save(ctx context.Context) (*Scholarshiptype, error) {
	if _, ok := sc.mutation.Scholarshiptypename(); !ok {
		return nil, &ValidationError{Name: "Scholarshiptypename", err: errors.New("ent: missing required field \"Scholarshiptypename\"")}
	}
	if v, ok := sc.mutation.Scholarshiptypename(); ok {
		if err := scholarshiptype.ScholarshiptypenameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Scholarshiptypename", err: fmt.Errorf("ent: validator failed for field \"Scholarshiptypename\": %w", err)}
		}
	}
	var (
		err  error
		node *Scholarshiptype
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScholarshiptypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ScholarshiptypeCreate) SaveX(ctx context.Context) *Scholarshiptype {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *ScholarshiptypeCreate) sqlSave(ctx context.Context) (*Scholarshiptype, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *ScholarshiptypeCreate) createSpec() (*Scholarshiptype, *sqlgraph.CreateSpec) {
	var (
		s     = &Scholarshiptype{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: scholarshiptype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scholarshiptype.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Scholarshiptypename(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: scholarshiptype.FieldScholarshiptypename,
		})
		s.Scholarshiptypename = value
	}
	if nodes := sc.mutation.ScholarshiptypeIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scholarshiptype.ScholarshiptypeIDTable,
			Columns: []string{scholarshiptype.ScholarshiptypeIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
