// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Varissara/app/ent/predicate"
	"github.com/Varissara/app/ent/scholarship"
	"github.com/Varissara/app/ent/semester"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SemesterUpdate is the builder for updating Semester entities.
type SemesterUpdate struct {
	config
	hooks      []Hook
	mutation   *SemesterMutation
	predicates []predicate.Semester
}

// Where adds a new predicate for the builder.
func (su *SemesterUpdate) Where(ps ...predicate.Semester) *SemesterUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetSemestername sets the Semestername field.
func (su *SemesterUpdate) SetSemestername(s string) *SemesterUpdate {
	su.mutation.SetSemestername(s)
	return su
}

// AddSemesterIDIDs adds the SemesterID edge to Scholarship by ids.
func (su *SemesterUpdate) AddSemesterIDIDs(ids ...int) *SemesterUpdate {
	su.mutation.AddSemesterIDIDs(ids...)
	return su
}

// AddSemesterID adds the SemesterID edges to Scholarship.
func (su *SemesterUpdate) AddSemesterID(s ...*Scholarship) *SemesterUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddSemesterIDIDs(ids...)
}

// Mutation returns the SemesterMutation object of the builder.
func (su *SemesterUpdate) Mutation() *SemesterMutation {
	return su.mutation
}

// RemoveSemesterIDIDs removes the SemesterID edge to Scholarship by ids.
func (su *SemesterUpdate) RemoveSemesterIDIDs(ids ...int) *SemesterUpdate {
	su.mutation.RemoveSemesterIDIDs(ids...)
	return su
}

// RemoveSemesterID removes SemesterID edges to Scholarship.
func (su *SemesterUpdate) RemoveSemesterID(s ...*Scholarship) *SemesterUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveSemesterIDIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SemesterUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Semestername(); ok {
		if err := semester.SemesternameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Semestername", err: fmt.Errorf("ent: validator failed for field \"Semestername\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SemesterMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SemesterUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SemesterUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SemesterUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SemesterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   semester.Table,
			Columns: semester.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: semester.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Semestername(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: semester.FieldSemestername,
		})
	}
	if nodes := su.mutation.RemovedSemesterIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   semester.SemesterIDTable,
			Columns: []string{semester.SemesterIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SemesterIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   semester.SemesterIDTable,
			Columns: []string{semester.SemesterIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{semester.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SemesterUpdateOne is the builder for updating a single Semester entity.
type SemesterUpdateOne struct {
	config
	hooks    []Hook
	mutation *SemesterMutation
}

// SetSemestername sets the Semestername field.
func (suo *SemesterUpdateOne) SetSemestername(s string) *SemesterUpdateOne {
	suo.mutation.SetSemestername(s)
	return suo
}

// AddSemesterIDIDs adds the SemesterID edge to Scholarship by ids.
func (suo *SemesterUpdateOne) AddSemesterIDIDs(ids ...int) *SemesterUpdateOne {
	suo.mutation.AddSemesterIDIDs(ids...)
	return suo
}

// AddSemesterID adds the SemesterID edges to Scholarship.
func (suo *SemesterUpdateOne) AddSemesterID(s ...*Scholarship) *SemesterUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddSemesterIDIDs(ids...)
}

// Mutation returns the SemesterMutation object of the builder.
func (suo *SemesterUpdateOne) Mutation() *SemesterMutation {
	return suo.mutation
}

// RemoveSemesterIDIDs removes the SemesterID edge to Scholarship by ids.
func (suo *SemesterUpdateOne) RemoveSemesterIDIDs(ids ...int) *SemesterUpdateOne {
	suo.mutation.RemoveSemesterIDIDs(ids...)
	return suo
}

// RemoveSemesterID removes SemesterID edges to Scholarship.
func (suo *SemesterUpdateOne) RemoveSemesterID(s ...*Scholarship) *SemesterUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveSemesterIDIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *SemesterUpdateOne) Save(ctx context.Context) (*Semester, error) {
	if v, ok := suo.mutation.Semestername(); ok {
		if err := semester.SemesternameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Semestername", err: fmt.Errorf("ent: validator failed for field \"Semestername\": %w", err)}
		}
	}

	var (
		err  error
		node *Semester
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SemesterMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SemesterUpdateOne) SaveX(ctx context.Context) *Semester {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SemesterUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SemesterUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SemesterUpdateOne) sqlSave(ctx context.Context) (s *Semester, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   semester.Table,
			Columns: semester.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: semester.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Semester.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Semestername(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: semester.FieldSemestername,
		})
	}
	if nodes := suo.mutation.RemovedSemesterIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   semester.SemesterIDTable,
			Columns: []string{semester.SemesterIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SemesterIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   semester.SemesterIDTable,
			Columns: []string{semester.SemesterIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Semester{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{semester.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
