// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Varissara/app/ent/scholarship"
	"github.com/Varissara/app/ent/studyplan"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// StudyplanCreate is the builder for creating a Studyplan entity.
type StudyplanCreate struct {
	config
	mutation *StudyplanMutation
	hooks    []Hook
}

// SetStudyplanname sets the Studyplanname field.
func (sc *StudyplanCreate) SetStudyplanname(s string) *StudyplanCreate {
	sc.mutation.SetStudyplanname(s)
	return sc
}

// AddStudyplanIDIDs adds the StudyplanID edge to Scholarship by ids.
func (sc *StudyplanCreate) AddStudyplanIDIDs(ids ...int) *StudyplanCreate {
	sc.mutation.AddStudyplanIDIDs(ids...)
	return sc
}

// AddStudyplanID adds the StudyplanID edges to Scholarship.
func (sc *StudyplanCreate) AddStudyplanID(s ...*Scholarship) *StudyplanCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddStudyplanIDIDs(ids...)
}

// Mutation returns the StudyplanMutation object of the builder.
func (sc *StudyplanCreate) Mutation() *StudyplanMutation {
	return sc.mutation
}

// Save creates the Studyplan in the database.
func (sc *StudyplanCreate) Save(ctx context.Context) (*Studyplan, error) {
	if _, ok := sc.mutation.Studyplanname(); !ok {
		return nil, &ValidationError{Name: "Studyplanname", err: errors.New("ent: missing required field \"Studyplanname\"")}
	}
	if v, ok := sc.mutation.Studyplanname(); ok {
		if err := studyplan.StudyplannameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Studyplanname", err: fmt.Errorf("ent: validator failed for field \"Studyplanname\": %w", err)}
		}
	}
	var (
		err  error
		node *Studyplan
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StudyplanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StudyplanCreate) SaveX(ctx context.Context) *Studyplan {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *StudyplanCreate) sqlSave(ctx context.Context) (*Studyplan, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *StudyplanCreate) createSpec() (*Studyplan, *sqlgraph.CreateSpec) {
	var (
		s     = &Studyplan{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: studyplan.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: studyplan.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Studyplanname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: studyplan.FieldStudyplanname,
		})
		s.Studyplanname = value
	}
	if nodes := sc.mutation.StudyplanIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   studyplan.StudyplanIDTable,
			Columns: []string{studyplan.StudyplanIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
