// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Varissara/app/ent/predicate"
	"github.com/Varissara/app/ent/scholarship"
	"github.com/Varissara/app/ent/studyplan"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// StudyplanUpdate is the builder for updating Studyplan entities.
type StudyplanUpdate struct {
	config
	hooks      []Hook
	mutation   *StudyplanMutation
	predicates []predicate.Studyplan
}

// Where adds a new predicate for the builder.
func (su *StudyplanUpdate) Where(ps ...predicate.Studyplan) *StudyplanUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetStudyplanname sets the Studyplanname field.
func (su *StudyplanUpdate) SetStudyplanname(s string) *StudyplanUpdate {
	su.mutation.SetStudyplanname(s)
	return su
}

// AddStudyplanIDIDs adds the StudyplanID edge to Scholarship by ids.
func (su *StudyplanUpdate) AddStudyplanIDIDs(ids ...int) *StudyplanUpdate {
	su.mutation.AddStudyplanIDIDs(ids...)
	return su
}

// AddStudyplanID adds the StudyplanID edges to Scholarship.
func (su *StudyplanUpdate) AddStudyplanID(s ...*Scholarship) *StudyplanUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddStudyplanIDIDs(ids...)
}

// Mutation returns the StudyplanMutation object of the builder.
func (su *StudyplanUpdate) Mutation() *StudyplanMutation {
	return su.mutation
}

// RemoveStudyplanIDIDs removes the StudyplanID edge to Scholarship by ids.
func (su *StudyplanUpdate) RemoveStudyplanIDIDs(ids ...int) *StudyplanUpdate {
	su.mutation.RemoveStudyplanIDIDs(ids...)
	return su
}

// RemoveStudyplanID removes StudyplanID edges to Scholarship.
func (su *StudyplanUpdate) RemoveStudyplanID(s ...*Scholarship) *StudyplanUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveStudyplanIDIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *StudyplanUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Studyplanname(); ok {
		if err := studyplan.StudyplannameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Studyplanname", err: fmt.Errorf("ent: validator failed for field \"Studyplanname\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StudyplanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *StudyplanUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StudyplanUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StudyplanUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StudyplanUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   studyplan.Table,
			Columns: studyplan.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: studyplan.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Studyplanname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: studyplan.FieldStudyplanname,
		})
	}
	if nodes := su.mutation.RemovedStudyplanIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   studyplan.StudyplanIDTable,
			Columns: []string{studyplan.StudyplanIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.StudyplanIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   studyplan.StudyplanIDTable,
			Columns: []string{studyplan.StudyplanIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studyplan.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// StudyplanUpdateOne is the builder for updating a single Studyplan entity.
type StudyplanUpdateOne struct {
	config
	hooks    []Hook
	mutation *StudyplanMutation
}

// SetStudyplanname sets the Studyplanname field.
func (suo *StudyplanUpdateOne) SetStudyplanname(s string) *StudyplanUpdateOne {
	suo.mutation.SetStudyplanname(s)
	return suo
}

// AddStudyplanIDIDs adds the StudyplanID edge to Scholarship by ids.
func (suo *StudyplanUpdateOne) AddStudyplanIDIDs(ids ...int) *StudyplanUpdateOne {
	suo.mutation.AddStudyplanIDIDs(ids...)
	return suo
}

// AddStudyplanID adds the StudyplanID edges to Scholarship.
func (suo *StudyplanUpdateOne) AddStudyplanID(s ...*Scholarship) *StudyplanUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddStudyplanIDIDs(ids...)
}

// Mutation returns the StudyplanMutation object of the builder.
func (suo *StudyplanUpdateOne) Mutation() *StudyplanMutation {
	return suo.mutation
}

// RemoveStudyplanIDIDs removes the StudyplanID edge to Scholarship by ids.
func (suo *StudyplanUpdateOne) RemoveStudyplanIDIDs(ids ...int) *StudyplanUpdateOne {
	suo.mutation.RemoveStudyplanIDIDs(ids...)
	return suo
}

// RemoveStudyplanID removes StudyplanID edges to Scholarship.
func (suo *StudyplanUpdateOne) RemoveStudyplanID(s ...*Scholarship) *StudyplanUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveStudyplanIDIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *StudyplanUpdateOne) Save(ctx context.Context) (*Studyplan, error) {
	if v, ok := suo.mutation.Studyplanname(); ok {
		if err := studyplan.StudyplannameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Studyplanname", err: fmt.Errorf("ent: validator failed for field \"Studyplanname\": %w", err)}
		}
	}

	var (
		err  error
		node *Studyplan
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StudyplanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StudyplanUpdateOne) SaveX(ctx context.Context) *Studyplan {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *StudyplanUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StudyplanUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StudyplanUpdateOne) sqlSave(ctx context.Context) (s *Studyplan, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   studyplan.Table,
			Columns: studyplan.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: studyplan.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Studyplan.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Studyplanname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: studyplan.FieldStudyplanname,
		})
	}
	if nodes := suo.mutation.RemovedStudyplanIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   studyplan.StudyplanIDTable,
			Columns: []string{studyplan.StudyplanIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.StudyplanIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   studyplan.StudyplanIDTable,
			Columns: []string{studyplan.StudyplanIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: scholarship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Studyplan{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studyplan.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
