// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// EducationlevelsColumns holds the columns for the "educationlevels" table.
	EducationlevelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "educationlevelname", Type: field.TypeString},
	}
	// EducationlevelsTable holds the schema information for the "educationlevels" table.
	EducationlevelsTable = &schema.Table{
		Name:        "educationlevels",
		Columns:     EducationlevelsColumns,
		PrimaryKey:  []*schema.Column{EducationlevelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ScholarshipsColumns holds the columns for the "scholarships" table.
	ScholarshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "schlolarshipname", Type: field.TypeString},
		{Name: "organization", Type: field.TypeString},
		{Name: "educationlevel_educationlevel_id", Type: field.TypeInt, Nullable: true},
		{Name: "scholarshiptype_scholarshiptype_id", Type: field.TypeInt, Nullable: true},
		{Name: "semester_semester_id", Type: field.TypeInt, Nullable: true},
		{Name: "studyplan_studyplan_id", Type: field.TypeInt, Nullable: true},
		{Name: "user_user_id", Type: field.TypeInt, Nullable: true},
	}
	// ScholarshipsTable holds the schema information for the "scholarships" table.
	ScholarshipsTable = &schema.Table{
		Name:       "scholarships",
		Columns:    ScholarshipsColumns,
		PrimaryKey: []*schema.Column{ScholarshipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "scholarships_educationlevels_EducationlevelID",
				Columns: []*schema.Column{ScholarshipsColumns[3]},

				RefColumns: []*schema.Column{EducationlevelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "scholarships_scholarshiptypes_ScholarshiptypeID",
				Columns: []*schema.Column{ScholarshipsColumns[4]},

				RefColumns: []*schema.Column{ScholarshiptypesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "scholarships_semesters_SemesterID",
				Columns: []*schema.Column{ScholarshipsColumns[5]},

				RefColumns: []*schema.Column{SemestersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "scholarships_studyplans_StudyplanID",
				Columns: []*schema.Column{ScholarshipsColumns[6]},

				RefColumns: []*schema.Column{StudyplansColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "scholarships_users_UserID",
				Columns: []*schema.Column{ScholarshipsColumns[7]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ScholarshiptypesColumns holds the columns for the "scholarshiptypes" table.
	ScholarshiptypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scholarshiptypename", Type: field.TypeString},
	}
	// ScholarshiptypesTable holds the schema information for the "scholarshiptypes" table.
	ScholarshiptypesTable = &schema.Table{
		Name:        "scholarshiptypes",
		Columns:     ScholarshiptypesColumns,
		PrimaryKey:  []*schema.Column{ScholarshiptypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SemestersColumns holds the columns for the "semesters" table.
	SemestersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "semestername", Type: field.TypeString},
	}
	// SemestersTable holds the schema information for the "semesters" table.
	SemestersTable = &schema.Table{
		Name:        "semesters",
		Columns:     SemestersColumns,
		PrimaryKey:  []*schema.Column{SemestersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// StudyplansColumns holds the columns for the "studyplans" table.
	StudyplansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "studyplanname", Type: field.TypeString},
	}
	// StudyplansTable holds the schema information for the "studyplans" table.
	StudyplansTable = &schema.Table{
		Name:        "studyplans",
		Columns:     StudyplansColumns,
		PrimaryKey:  []*schema.Column{StudyplansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "useremail", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EducationlevelsTable,
		ScholarshipsTable,
		ScholarshiptypesTable,
		SemestersTable,
		StudyplansTable,
		UsersTable,
	}
)

func init() {
	ScholarshipsTable.ForeignKeys[0].RefTable = EducationlevelsTable
	ScholarshipsTable.ForeignKeys[1].RefTable = ScholarshiptypesTable
	ScholarshipsTable.ForeignKeys[2].RefTable = SemestersTable
	ScholarshipsTable.ForeignKeys[3].RefTable = StudyplansTable
	ScholarshipsTable.ForeignKeys[4].RefTable = UsersTable
}
