/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarship,
    EntScholarshipFromJSON,
    EntScholarshipFromJSONTyped,
    EntScholarshipToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEducationlevelEdges
 */
export interface EntEducationlevelEdges {
    /**
     * EducationlevelID holds the value of the EducationlevelID edge.
     * @type {Array<EntScholarship>}
     * @memberof EntEducationlevelEdges
     */
    educationlevelID?: Array<EntScholarship>;
}

export function EntEducationlevelEdgesFromJSON(json: any): EntEducationlevelEdges {
    return EntEducationlevelEdgesFromJSONTyped(json, false);
}

export function EntEducationlevelEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEducationlevelEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'educationlevelID': !exists(json, 'educationlevelID') ? undefined : ((json['educationlevelID'] as Array<any>).map(EntScholarshipFromJSON)),
    };
}

export function EntEducationlevelEdgesToJSON(value?: EntEducationlevelEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'educationlevelID': value.educationlevelID === undefined ? undefined : ((value.educationlevelID as Array<any>).map(EntScholarshipToJSON)),
    };
}


