/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarship,
    EntScholarshipFromJSON,
    EntScholarshipFromJSONTyped,
    EntScholarshipToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntScholarshiptypeEdges
 */
export interface EntScholarshiptypeEdges {
    /**
     * ScholarshiptypeID holds the value of the ScholarshiptypeID edge.
     * @type {Array<EntScholarship>}
     * @memberof EntScholarshiptypeEdges
     */
    scholarshiptypeID?: Array<EntScholarship>;
}

export function EntScholarshiptypeEdgesFromJSON(json: any): EntScholarshiptypeEdges {
    return EntScholarshiptypeEdgesFromJSONTyped(json, false);
}

export function EntScholarshiptypeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntScholarshiptypeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scholarshiptypeID': !exists(json, 'scholarshiptypeID') ? undefined : ((json['scholarshiptypeID'] as Array<any>).map(EntScholarshipFromJSON)),
    };
}

export function EntScholarshiptypeEdgesToJSON(value?: EntScholarshiptypeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scholarshiptypeID': value.scholarshiptypeID === undefined ? undefined : ((value.scholarshiptypeID as Array<any>).map(EntScholarshipToJSON)),
    };
}


