/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEducationlevel,
    EntEducationlevelFromJSON,
    EntEducationlevelFromJSONTyped,
    EntEducationlevelToJSON,
    EntScholarshiptype,
    EntScholarshiptypeFromJSON,
    EntScholarshiptypeFromJSONTyped,
    EntScholarshiptypeToJSON,
    EntSemester,
    EntSemesterFromJSON,
    EntSemesterFromJSONTyped,
    EntSemesterToJSON,
    EntStudyplan,
    EntStudyplanFromJSON,
    EntStudyplanFromJSONTyped,
    EntStudyplanToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntScholarshipEdges
 */
export interface EntScholarshipEdges {
    /**
     * 
     * @type {EntEducationlevel}
     * @memberof EntScholarshipEdges
     */
    educationlevelID?: EntEducationlevel;
    /**
     * 
     * @type {EntScholarshiptype}
     * @memberof EntScholarshipEdges
     */
    scholarshiptypeID?: EntScholarshiptype;
    /**
     * 
     * @type {EntSemester}
     * @memberof EntScholarshipEdges
     */
    semesterID?: EntSemester;
    /**
     * 
     * @type {EntStudyplan}
     * @memberof EntScholarshipEdges
     */
    studyplanID?: EntStudyplan;
    /**
     * 
     * @type {EntUser}
     * @memberof EntScholarshipEdges
     */
    userID?: EntUser;
}

export function EntScholarshipEdgesFromJSON(json: any): EntScholarshipEdges {
    return EntScholarshipEdgesFromJSONTyped(json, false);
}

export function EntScholarshipEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntScholarshipEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'educationlevelID': !exists(json, 'educationlevelID') ? undefined : EntEducationlevelFromJSON(json['educationlevelID']),
        'scholarshiptypeID': !exists(json, 'scholarshiptypeID') ? undefined : EntScholarshiptypeFromJSON(json['scholarshiptypeID']),
        'semesterID': !exists(json, 'semesterID') ? undefined : EntSemesterFromJSON(json['semesterID']),
        'studyplanID': !exists(json, 'studyplanID') ? undefined : EntStudyplanFromJSON(json['studyplanID']),
        'userID': !exists(json, 'userID') ? undefined : EntUserFromJSON(json['userID']),
    };
}

export function EntScholarshipEdgesToJSON(value?: EntScholarshipEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'educationlevelID': EntEducationlevelToJSON(value.educationlevelID),
        'scholarshiptypeID': EntScholarshiptypeToJSON(value.scholarshiptypeID),
        'semesterID': EntSemesterToJSON(value.semesterID),
        'studyplanID': EntStudyplanToJSON(value.studyplanID),
        'userID': EntUserToJSON(value.userID),
    };
}


