/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarshiptypeEdges,
    EntScholarshiptypeEdgesFromJSON,
    EntScholarshiptypeEdgesFromJSONTyped,
    EntScholarshiptypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntScholarshiptype
 */
export interface EntScholarshiptype {
    /**
     * Scholarshiptypename holds the value of the "Scholarshiptypename" field.
     * @type {string}
     * @memberof EntScholarshiptype
     */
    scholarshiptypename?: string;
    /**
     * 
     * @type {EntScholarshiptypeEdges}
     * @memberof EntScholarshiptype
     */
    edges?: EntScholarshiptypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntScholarshiptype
     */
    id?: number;
}

export function EntScholarshiptypeFromJSON(json: any): EntScholarshiptype {
    return EntScholarshiptypeFromJSONTyped(json, false);
}

export function EntScholarshiptypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntScholarshiptype {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scholarshiptypename': !exists(json, 'Scholarshiptypename') ? undefined : json['Scholarshiptypename'],
        'edges': !exists(json, 'edges') ? undefined : EntScholarshiptypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntScholarshiptypeToJSON(value?: EntScholarshiptype | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Scholarshiptypename': value.scholarshiptypename,
        'edges': EntScholarshiptypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


