/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntScholarshipEdges,
    EntScholarshipEdgesFromJSON,
    EntScholarshipEdgesFromJSONTyped,
    EntScholarshipEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntScholarship
 */
export interface EntScholarship {
    /**
     * Schlolarshipname holds the value of the "Schlolarshipname" field.
     * @type {string}
     * @memberof EntScholarship
     */
    schlolarshipname?: string;
    /**
     * 
     * @type {EntScholarshipEdges}
     * @memberof EntScholarship
     */
    edges?: EntScholarshipEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntScholarship
     */
    id?: number;
    /**
     * Organization holds the value of the "organization" field.
     * @type {string}
     * @memberof EntScholarship
     */
    organization?: string;
}

export function EntScholarshipFromJSON(json: any): EntScholarship {
    return EntScholarshipFromJSONTyped(json, false);
}

export function EntScholarshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntScholarship {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schlolarshipname': !exists(json, 'Schlolarshipname') ? undefined : json['Schlolarshipname'],
        'edges': !exists(json, 'edges') ? undefined : EntScholarshipEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'organization': !exists(json, 'organization') ? undefined : json['organization'],
    };
}

export function EntScholarshipToJSON(value?: EntScholarship | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Schlolarshipname': value.schlolarshipname,
        'edges': EntScholarshipEdgesToJSON(value.edges),
        'id': value.id,
        'organization': value.organization,
    };
}


