// Code generated by entc, DO NOT EDIT.

package educationlevel

const (
	// Label holds the string label denoting the educationlevel type in the database.
	Label = "educationlevel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEducationlevelname holds the string denoting the educationlevelname field in the database.
	FieldEducationlevelname = "educationlevelname"

	// EdgeEducationlevelID holds the string denoting the educationlevelid edge name in mutations.
	EdgeEducationlevelID = "EducationlevelID"

	// Table holds the table name of the educationlevel in the database.
	Table = "educationlevels"
	// EducationlevelIDTable is the table the holds the EducationlevelID relation/edge.
	EducationlevelIDTable = "scholarships"
	// EducationlevelIDInverseTable is the table name for the Scholarship entity.
	// It exists in this package in order to avoid circular dependency with the "scholarship" package.
	EducationlevelIDInverseTable = "scholarships"
	// EducationlevelIDColumn is the table column denoting the EducationlevelID relation/edge.
	EducationlevelIDColumn = "educationlevel_educationlevel_id"
)

// Columns holds all SQL columns for educationlevel fields.
var Columns = []string{
	FieldID,
	FieldEducationlevelname,
}

var (
	// EducationlevelnameValidator is a validator for the "Educationlevelname" field. It is called by the builders before save.
	EducationlevelnameValidator func(string) error
)
