// Code generated by entc, DO NOT EDIT.

package educationlevel

import (
	"github.com/Varissara/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Educationlevelname applies equality check predicate on the "Educationlevelname" field. It's identical to EducationlevelnameEQ.
func Educationlevelname(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameEQ applies the EQ predicate on the "Educationlevelname" field.
func EducationlevelnameEQ(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameNEQ applies the NEQ predicate on the "Educationlevelname" field.
func EducationlevelnameNEQ(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameIn applies the In predicate on the "Educationlevelname" field.
func EducationlevelnameIn(vs ...string) predicate.Educationlevel {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Educationlevel(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldEducationlevelname), v...))
	})
}

// EducationlevelnameNotIn applies the NotIn predicate on the "Educationlevelname" field.
func EducationlevelnameNotIn(vs ...string) predicate.Educationlevel {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Educationlevel(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldEducationlevelname), v...))
	})
}

// EducationlevelnameGT applies the GT predicate on the "Educationlevelname" field.
func EducationlevelnameGT(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameGTE applies the GTE predicate on the "Educationlevelname" field.
func EducationlevelnameGTE(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameLT applies the LT predicate on the "Educationlevelname" field.
func EducationlevelnameLT(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameLTE applies the LTE predicate on the "Educationlevelname" field.
func EducationlevelnameLTE(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameContains applies the Contains predicate on the "Educationlevelname" field.
func EducationlevelnameContains(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameHasPrefix applies the HasPrefix predicate on the "Educationlevelname" field.
func EducationlevelnameHasPrefix(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameHasSuffix applies the HasSuffix predicate on the "Educationlevelname" field.
func EducationlevelnameHasSuffix(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameEqualFold applies the EqualFold predicate on the "Educationlevelname" field.
func EducationlevelnameEqualFold(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldEducationlevelname), v))
	})
}

// EducationlevelnameContainsFold applies the ContainsFold predicate on the "Educationlevelname" field.
func EducationlevelnameContainsFold(v string) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldEducationlevelname), v))
	})
}

// HasEducationlevelID applies the HasEdge predicate on the "EducationlevelID" edge.
func HasEducationlevelID() predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EducationlevelIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EducationlevelIDTable, EducationlevelIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEducationlevelIDWith applies the HasEdge predicate on the "EducationlevelID" edge with a given conditions (other predicates).
func HasEducationlevelIDWith(preds ...predicate.Scholarship) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EducationlevelIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EducationlevelIDTable, EducationlevelIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Educationlevel) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Educationlevel) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Educationlevel) predicate.Educationlevel {
	return predicate.Educationlevel(func(s *sql.Selector) {
		p(s.Not())
	})
}
