// Code generated by entc, DO NOT EDIT.

package scholarshiptype

const (
	// Label holds the string label denoting the scholarshiptype type in the database.
	Label = "scholarshiptype"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScholarshiptypename holds the string denoting the scholarshiptypename field in the database.
	FieldScholarshiptypename = "scholarshiptypename"

	// EdgeScholarshiptypeID holds the string denoting the scholarshiptypeid edge name in mutations.
	EdgeScholarshiptypeID = "ScholarshiptypeID"

	// Table holds the table name of the scholarshiptype in the database.
	Table = "scholarshiptypes"
	// ScholarshiptypeIDTable is the table the holds the ScholarshiptypeID relation/edge.
	ScholarshiptypeIDTable = "scholarships"
	// ScholarshiptypeIDInverseTable is the table name for the Scholarship entity.
	// It exists in this package in order to avoid circular dependency with the "scholarship" package.
	ScholarshiptypeIDInverseTable = "scholarships"
	// ScholarshiptypeIDColumn is the table column denoting the ScholarshiptypeID relation/edge.
	ScholarshiptypeIDColumn = "scholarshiptype_scholarshiptype_id"
)

// Columns holds all SQL columns for scholarshiptype fields.
var Columns = []string{
	FieldID,
	FieldScholarshiptypename,
}

var (
	// ScholarshiptypenameValidator is a validator for the "Scholarshiptypename" field. It is called by the builders before save.
	ScholarshiptypenameValidator func(string) error
)
