// Code generated by entc, DO NOT EDIT.

package scholarshiptype

import (
	"github.com/Varissara/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Scholarshiptypename applies equality check predicate on the "Scholarshiptypename" field. It's identical to ScholarshiptypenameEQ.
func Scholarshiptypename(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameEQ applies the EQ predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameEQ(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameNEQ applies the NEQ predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameNEQ(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameIn applies the In predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameIn(vs ...string) predicate.Scholarshiptype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldScholarshiptypename), v...))
	})
}

// ScholarshiptypenameNotIn applies the NotIn predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameNotIn(vs ...string) predicate.Scholarshiptype {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldScholarshiptypename), v...))
	})
}

// ScholarshiptypenameGT applies the GT predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameGT(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameGTE applies the GTE predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameGTE(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameLT applies the LT predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameLT(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameLTE applies the LTE predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameLTE(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameContains applies the Contains predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameContains(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameHasPrefix applies the HasPrefix predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameHasPrefix(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameHasSuffix applies the HasSuffix predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameHasSuffix(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameEqualFold applies the EqualFold predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameEqualFold(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldScholarshiptypename), v))
	})
}

// ScholarshiptypenameContainsFold applies the ContainsFold predicate on the "Scholarshiptypename" field.
func ScholarshiptypenameContainsFold(v string) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldScholarshiptypename), v))
	})
}

// HasScholarshiptypeID applies the HasEdge predicate on the "ScholarshiptypeID" edge.
func HasScholarshiptypeID() predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshiptypeIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ScholarshiptypeIDTable, ScholarshiptypeIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScholarshiptypeIDWith applies the HasEdge predicate on the "ScholarshiptypeID" edge with a given conditions (other predicates).
func HasScholarshiptypeIDWith(preds ...predicate.Scholarship) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ScholarshiptypeIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ScholarshiptypeIDTable, ScholarshiptypeIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Scholarshiptype) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Scholarshiptype) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Scholarshiptype) predicate.Scholarshiptype {
	return predicate.Scholarshiptype(func(s *sql.Selector) {
		p(s.Not())
	})
}
